"""Mutual-information estimation interfaces and implementations."""

from shannonist.mi.ba import (
    EntropyEstimator,
    FlowEntropyEstimator,
    FlowProposal,
    GaussianEntropyEstimator,
    GaussianProposal,
    JointBA,
    JointBAOutput,
    PairwiseBA,
    PairwiseBAOutput,
    SampledPairwiseBA,
    SampledPairwiseBAOutput,
    Proposal,
    StandardNormalEntropyEstimator,
    make_entropy_estimator,
    make_proposal,
    joint_ba_loss,
    pairwise_ba_loss,
    sampled_pairwise_ba_loss,
)
from shannonist.mi.data import (
    CorrelatedGausian,
    LatentPairwiseCorrelatedGaussian,
    PairwiseCorrelatedGaussian,
    tensordict_collate,
    tensordict_passthrough,
)
from shannonist.mi.flo import (
    JointFLO,
    JointFLOOutput,
    ContrastivePairwiseFLO,
    ContrastivePairwiseFLow,
    ContrastivePairwiseFLOOutput,
    PairwiseFLO,
    PairwiseFLOOutput,
    contrastive_pairwise_flo_loss,
    flo_loss,
    pairwise_flo_loss,
)
from shannonist.mi.types import MIBatch, MIEstimate, PairwiseMIBatch

__all__ = [
    "JointFLO",
    "JointFLOOutput",
    "ContrastivePairwiseFLO",
    "ContrastivePairwiseFLow",
    "ContrastivePairwiseFLOOutput",
    "CorrelatedGausian",
    "EntropyEstimator",
    "FlowEntropyEstimator",
    "FlowProposal",
    "GaussianEntropyEstimator",
    "GaussianProposal",
    "LatentPairwiseCorrelatedGaussian",
    "PairwiseFLO",
    "PairwiseFLOOutput",
    "JointBA",
    "JointBAOutput",
    "PairwiseBA",
    "PairwiseBAOutput",
    "SampledPairwiseBA",
    "SampledPairwiseBAOutput",
    "PairwiseCorrelatedGaussian",
    "PairwiseMIBatch",
    "Proposal",
    "StandardNormalEntropyEstimator",
    "make_entropy_estimator",
    "make_proposal",
    "contrastive_pairwise_flo_loss",
    "flo_loss",
    "pairwise_flo_loss",
    "joint_ba_loss",
    "pairwise_ba_loss",
    "sampled_pairwise_ba_loss",
    "tensordict_collate",
    "tensordict_passthrough",
    "MIBatch",
    "MIEstimate",
]
